project:
  type: website
  output-dir: docs

website:
  title: "BPLIM"
  favicon: images/data.jpg
  #downloads: [pdf, epub]
  search: 
    location: navbar
    type: overlay

  navbar:
    #title: true
    search: true
    #logo: images/BdP_Logo_5.png
    background: primary
    tools:
      - icon: youtube
        href: https://www.youtube.com/@BancodePortugalOficial/featured
    left:
      - text: "Home"
        href: index.qmd
      - text: "Website" 
        href: https://bplim.bportugal.pt/
      - text: "Instructional Videos"
        href: https://bplim.github.io/Manuals/
      - text: "Guides"
        href: ../Manuals/Guides/01_Guide_for_Researchers/Guide_for_researchers_v072024.qmd
      - text: "Data Manuals"
        href: manuals.qmd
      - text: "Tools"
        href: https://github.com/BPLIM/Tools/
      - text: "Workshops"
        href: https://github.com/BPLIM/Workshops/


  sidebar:
    style: "docked"
    #search: true
    border: true
    collapse-level: 3
    pinned: false
    background: "#e2ecf1"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Website" 
        href: https://bplim.bportugal.pt/
      - text: "Instructional Videos"
        href: https://bplim.github.io/Manuals/
      - text: "Guides"
        href: ../Manuals/Guides/01_Guide_for_Researchers/Guide_for_researchers_v072024.qmd
      - text: "Data Manuals"
        href: manuals.qmd
      - text: "Tools"
        href: https://github.com/BPLIM/Tools/
      - text: "Workshops"
        href: https://github.com/BPLIM/Workshops/


  page-footer: 
    left: "BPLIM@bportugal.pt"
    right: This page was built with <a href="https://quarto.org/">Quarto</a>.
      

format:
  html:
    #theme: morph
    theme: Flatly
    css: styles.css
    toc: true
    
 