project:
  type: website
  #output-dir: docs
  

website:
  title: "BPLIM"
  favicon: images/data.jpg
  #downloads: [pdf, epub] # Enables PDF and EPUB downloads
  search: 
    location: navbar
    type: overlay

  navbar:
    #title: true
    search: true
    #logo: images/BdP_Logo_5.png
    #downloads: [pdf, epub] 
    background: primary
    tools:
      - icon: youtube
        href: https://www.youtube.com/@BancodePortugalOficial/featured
    left:
      - text: "Home"
        href: index.qmd
      - text: "Website" 
        href: https://bplim.bportugal.pt/
      - text: "Instructional Videos"
        href: https://bplim.github.io/Manuals/
      - text: "Guides"
        href: guides.qmd
        menu:
          - text: "Guide for researchers"
            href: Guides/01_Guide_for_Researchers/Guide_for_researchers_v072024.qmd
          - text: "Datasets guide"
            href: Guides/02_BPLIM_Datasets_Guide/BPLIM_Datasets_Guide_v102024.qmd
          - text: "External server"
            href: Guides/03_External_Server/External_Server_Guide.qmd
          - text: "Using Git"
            href: Guides/04_How_to_use_Git/Guide_Git.qmd
          - text: "How to use containers"
            href: Guides/05_How_to_use_Containers/Guide_Containers.qmd
          - text: "Output control"
            href: Guides/06_Output_Control/Output_Control_Guide.qmd
          - text: "Work with Pseudo-Data"
            href: Guides/07_Working_with_Pseudo-Data/pseudo_data_guide.qmd
      - text: "Data Manuals"
        href: data_manuals.qmd
      - text: "Tools"
        href: https://github.com/BPLIM/Tools/
      - text: "Workshops"
        href: https://github.com/BPLIM/Workshops/


  sidebar:
    style: "docked"
    #search: true
    #downloads: [pdf, epub] 
    border: true
    collapse-level: 3
    pinned: true
    background: "#e2ecf1"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Website" 
        href: https://bplim.bportugal.pt/
      - text: "Instructional Videos"
        href: https://bplim.github.io/Manuals/
      - section: "Guides"
        href: guides.qmd
        contents:
          - text: "Guide for researchers"
            href: Guides/01_Guide_for_Researchers/Guide_for_researchers_v072024.qmd
          - text: "Datasets guide"
            href: Guides/02_BPLIM_Datasets_Guide/BPLIM_Datasets_Guide_v102024.qmd
          - text: "External server"
            href: Guides/03_External_Server/External_Server_Guide.qmd
          - text: "Using Git"
            href: Guides/04_How_to_use_Git/Guide_Git.qmd
          - text: "How to use containers"
            href: Guides/05_How_to_use_Containers/Guide_Containers.qmd
          - text: "Output control"
            href: Guides/06_Output_Control/Output_Control_Guide.qmd
          - text: "Work with Pseudo-Data"
            href: Guides/07_Working_with_Pseudo-Data/pseudo_data_guide.qmd
      - text: "Data Manuals"
        href: data_manuals.qmd
      - text: "Tools"
        href: https://github.com/BPLIM/Tools/
      - text: "Workshops"
        href: https://github.com/BPLIM/Workshops/


  page-footer: 
    left: "BPLIM@bportugal.pt"
    right: This page was built with <a href="https://quarto.org/">Quarto</a>.
      

format:
  html:
    #theme: morph
    theme: Flatly
    css: styles.css
    toc: true
    

  #pdf:
    #output-file: docs/BPLIM.pdf
    #toc: true
    #number-sections: true

  #epub:
    #output-file: docs/BPLIM.epub
    #toc: true
