project:
  type: website
  output-dir: docs

book:
  title: "BPLIM's page"
  author: "Banco de Portugal's Microdata Research Laboratory (BPLIM)"
  date: "15/10/2024"
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  #cover-image: images/BdP_Logo_2.png 
  search: true
  
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
