---
format: 
  html:
    theme: Flatly
    css: styles.css
    toc: true
---


# Data Manuals

### Bank Balance Sheet (BBS)

The Bank Balance Sheet Database (BBS) reports detailed information on the assets and liabilities of all the monetary financial institutions (MFIs) operating in Portugal. The dataset contains monthly data, from 1997 onwards. BPLIM has been producing an annual product based on this data since 2021.

##### [JUN21 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/BBS/JUN21)
##### [JUN22 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/BBS/JUN22)
##### [JUN23 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/BBS/JUN23)
##### [JUN24 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/BBS/JUN24)
    

### Central Balance Sheet (CB)


The Central Balance Sheet Database (CB) provides economic and financial data on non-financial corporations operating in Portugal, with annual data from 2006 onwards. Data was reported using the Plano Oficial de Contabilidade (POC) until 2009, and since 2010, it follows the Sistema de Normalização Contabilística (SNC), reflecting a significant structural change in data organization. BPLIM has been producing an annual product based on this data since 2019.

##### [JUN19 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN19)
##### [JUN20 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN20)
##### [JUN21 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN21)
##### [JUN22 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN22)
##### [JUN23 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN23)
##### [JUN24 Extraction](https://github.com/BPLIM/Manuals/tree/master/Data/CB/JUN24)



### [CBHP](https://github.com/BPLIM/Manuals/tree/master/Data/CBHP)

### [CRC](https://github.com/BPLIM/Manuals/tree/master/Data/CRC)

### [GE](https://github.com/BPLIM/Manuals/tree/master/Data/GE)

### [HCRC](https://github.com/BPLIM/Manuals/tree/master/Data/HCRC)

### [IBACH](https://github.com/BPLIM/Manuals/tree/master/Data/IBACH)

### [IREE](https://github.com/BPLIM/Manuals/tree/master/Data/IREE)

### [SI](https://github.com/BPLIM/Manuals/tree/master/Data/SI)

### [SLB](https://github.com/BPLIM/Manuals/tree/master/Data/SLB)
